# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml

rest_command:
  turn_fan_off_rest:
    url: "http://esp32-rf.local/api/fan"
    method: post
    headers:
      Content-Type: "application/json"
    payload: '{{ fan_name | tojson }}'

  turn_fan_off:
    url: "http://esp32-rf.local/transmit?name={{ (fan_name ~ '_off') | urlencode }}"
    method: post

script:
  turn_off_fan_office:
    alias: "Turn Off Fan - Office"
    sequence:
      - service: rest_command.turn_fan_off
        data:
          fan_name: office